### ISSUE TITLE
No module name cv2

### ISSUE THREAD

**Issue by harsh1702** [dilawar/PlotDigitizer#8]
After installing as per the instructions when I try to run the either of the commands
`plotdigitizer --help`
`plotdigitizer ./figures/trimmed.png -p 0,0 -p 10,0 -p 0,1`

the following error shows up, how do I get by this error

Traceback (most recent call last):
  File "/home/harsh/.local/bin/plotdigitizer", line 7, in <module>
    from PlotDigitizer.plotdigitizer import main
  File "/home/harsh/.local/lib/python3.6/site-packages/PlotDigitizer/plotdigitizer.py", line 13, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by dilawar** [comment]
You need to install opencv python module. 

On linux,  https://pkgs.org/download/python3-opencv

On some distros, pip may be able to install https://pypi.org/project/opencv-python/ 

```bash
python3 -m pip install opencv-python
```
